[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
mypy_path = "scripts"
explicit_package_bases = true
namespace_packages = true
check_untyped_defs = true
disallow_untyped_defs = false

[[tool.mypy.overrides]]
module = "qlty.*"
disallow_untyped_defs = true

[tool.pylint.master]
# Add scripts to python path for pylint
init-hook = 'import sys; sys.path.append("./scripts")'

[tool.pylint.format]
max-line-length = 100

[tool.pylint.messages_control]
disable = [
    "C0114", # missing-module-docstring
    "C0115", # missing-class-docstring
    "C0116", # missing-function-docstring
]
